# Generated by Django 4.2.7 on 2023-11-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Email', models.TextField()),
                ('Password', models.TextField()),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('PassengerID', models.IntegerField()),
                ('RouteID', models.IntegerField()),
                ('On', models.IntegerField()),
                ('Off', models.IntegerField()),
                ('Status', models.BooleanField(default=True)),
                ('Work_Status', models.BooleanField(default=True)),
                ('Time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Request',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('RouteID', models.AutoField(primary_key=True, serialize=False)),
                ('DriverID', models.IntegerField()),
                ('Status', models.BooleanField(default=True)),
                ('Time', models.DateTimeField()),
                ('Work_Status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Route',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('StationID', models.AutoField(primary_key=True, serialize=False)),
                ('StationName', models.TextField()),
            ],
            options={
                'db_table': 'Station',
            },
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RouteID', models.IntegerField()),
                ('StationID', models.IntegerField()),
                ('Time', models.DateTimeField()),
            ],
            options={
                'db_table': 'RouteStation',
                'unique_together': {('StationID', 'RouteID')},
            },
        ),
        migrations.CreateModel(
            name='RoutePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassengerID', models.IntegerField()),
                ('RouteID', models.IntegerField()),
                ('On', models.IntegerField()),
                ('Off', models.IntegerField()),
                ('Work_Status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'RoutePassenger',
                'unique_together': {('PassengerID', 'RouteID')},
            },
        ),
    ]
