# Generated by Django 4.2.7 on 2023-11-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('UserID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(default='')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.TextField(default='')),
                ('Avatar', models.URLField(default='')),
                ('Phone', models.TextField(default='')),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('RequestID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Status', models.BooleanField(default=True)),
                ('Work_Status', models.BooleanField(default=True)),
                ('Time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Request',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('RouteID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Status', models.TextField(default='available')),
                ('Time', models.DateField()),
                ('Work_Status', models.BooleanField(default=True)),
                ('Car_Color', models.TextField()),
                ('Car_Capacity', models.IntegerField()),
                ('LicensePlateNumber', models.TextField()),
                ('Driver', models.ForeignKey(db_column='DriverID', on_delete=django.db.models.deletion.PROTECT, related_name='Driver_Routes', to='uber_app.account')),
            ],
            options={
                'db_table': 'Route',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('StationID', models.AutoField(primary_key=True, serialize=False)),
                ('StationName', models.TextField()),
                ('Enable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Station',
            },
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Route', models.ForeignKey(db_column='RouteID', on_delete=django.db.models.deletion.CASCADE, to='uber_app.route')),
                ('Station', models.ForeignKey(db_column='StationID', on_delete=django.db.models.deletion.PROTECT, to='uber_app.station')),
            ],
            options={
                'db_table': 'RouteStation',
            },
        ),
        migrations.CreateModel(
            name='RoutePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_Status', models.BooleanField(default=True)),
                ('Off', models.ForeignKey(db_column='Off', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uber_app.station')),
                ('On', models.ForeignKey(db_column='On', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uber_app.station')),
                ('Passenger', models.ForeignKey(db_column='PassengerID', on_delete=django.db.models.deletion.PROTECT, to='uber_app.account')),
                ('Request', models.ForeignKey(db_column='RequestID', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uber_app.request')),
                ('Route', models.ForeignKey(db_column='RouteID', on_delete=django.db.models.deletion.PROTECT, to='uber_app.route')),
            ],
            options={
                'db_table': 'RoutePassenger',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='Passengers',
            field=models.ManyToManyField(related_name='Passenger_Routes', through='uber_app.RoutePassenger', to='uber_app.account'),
        ),
        migrations.AddField(
            model_name='route',
            name='Stations',
            field=models.ManyToManyField(related_name='+', through='uber_app.RouteStation', to='uber_app.station'),
        ),
        migrations.AddField(
            model_name='request',
            name='Off',
            field=models.ForeignKey(db_column='Off', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uber_app.station'),
        ),
        migrations.AddField(
            model_name='request',
            name='On',
            field=models.ForeignKey(db_column='On', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uber_app.station'),
        ),
        migrations.AddField(
            model_name='request',
            name='Passenger',
            field=models.ForeignKey(db_column='PassengerID', on_delete=django.db.models.deletion.PROTECT, related_name='Requests', to='uber_app.account'),
        ),
        migrations.AddField(
            model_name='request',
            name='Route',
            field=models.ForeignKey(db_column='RouteID', on_delete=django.db.models.deletion.PROTECT, related_name='Requests', to='uber_app.route'),
        ),
    ]
