# Generated by Django 5.0 on 2023-12-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestation',
            name='Status',
            field=models.TextField(default='normal'),
        ),
    ]
