# Generated by Django 4.2.7 on 2023-11-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Email',
            field=models.TextField(unique=True),
        ),
    ]
