# Generated by Django 4.2.7 on 2023-11-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber_app', '0002_alter_account_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='StationID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='StationName',
            new_name='name',
        ),
    ]
