# Generated by Django 5.0 on 2023-12-11 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber_app', '0002_routestation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Off',
            field=models.ForeignKey(db_column='Off', on_delete=django.db.models.deletion.PROTECT, related_name='OffRequests', to='uber_app.routestation'),
        ),
        migrations.AlterField(
            model_name='request',
            name='On',
            field=models.ForeignKey(db_column='On', on_delete=django.db.models.deletion.PROTECT, related_name='OnRequests', to='uber_app.routestation'),
        ),
    ]
