# Generated by Django 4.2.7 on 2023-12-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber_app', '0002_route_car_model_alter_route_car_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Status',
            field=models.TextField(default='new'),
        ),
    ]
