# Generated by Django 4.2.7 on 2023-11-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber_app', '0003_rename_stationid_station_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='id',
            new_name='StationID',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='name',
            new_name='StationName',
        ),
    ]
