# Generated by Django 4.2.7 on 2023-12-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uber_app', '0003_alter_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Read', models.BooleanField(default=False)),
                ('For', models.TextField()),
                ('Category', models.TextField()),
                ('Request', models.ForeignKey(db_column='RequestID', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uber_app.request')),
                ('Route', models.ForeignKey(db_column='RouteID', on_delete=django.db.models.deletion.PROTECT, related_name='Notifications', to='uber_app.route')),
                ('User', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, related_name='Notification_Users', to='uber_app.account')),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
    ]
