# Generated by Django 4.2.7 on 2023-12-09 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber_app', '0005_request_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
