# Generated by Django 4.2.7 on 2023-12-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uber_app', '0006_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Driver_Notification_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='Passenger_Notification_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Request',
            field=models.ForeignKey(db_column='RequestID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uber_app.request'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Route',
            field=models.ForeignKey(db_column='RouteID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uber_app.route'),
        ),
    ]
